import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "CRM",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className="bg-white">{children}</body>
        </html>
    );
}
