import type { Metadata } from "next";
import Menu from "./settings/components/Menu";
import "./globals.css";

export const metadata: Metadata = {
    title: "CRM",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className="bg-white">
                <header>
                    <Menu />
                </header>
                {children}
            </body>
        </html>
    );
}
